export interface IconDef {
  name: string;
  class: string;
}

export const FONTAWESOME_CATEGORIES: Record<string, IconDef[]> = {
  "Common & UI": [
    { name: "Star", class: "fa-solid fa-star" },
    { name: "Star (Outline)", class: "fa-regular fa-star" },
    { name: "Heart", class: "fa-solid fa-heart" },
    { name: "Heart (Outline)", class: "fa-regular fa-heart" },
    { name: "Check", class: "fa-solid fa-check" },
    { name: "Check Double", class: "fa-solid fa-check-double" },
    { name: "Check Circle", class: "fa-solid fa-circle-check" },
    { name: "Check Circle (Outline)", class: "fa-regular fa-circle-check" },
    { name: "X Mark / Close", class: "fa-solid fa-xmark" },
    { name: "X Circle", class: "fa-solid fa-circle-xmark" },
    { name: "Plus", class: "fa-solid fa-plus" },
    { name: "Plus Circle", class: "fa-solid fa-circle-plus" },
    { name: "Minus", class: "fa-solid fa-minus" },
    { name: "Minus Circle", class: "fa-solid fa-circle-minus" },
    { name: "Question", class: "fa-solid fa-question" },
    { name: "Question Circle", class: "fa-solid fa-circle-question" },
    { name: "Info", class: "fa-solid fa-info" },
    { name: "Info Circle", class: "fa-solid fa-circle-info" },
    { name: "Exclamation", class: "fa-solid fa-exclamation" },
    { name: "Exclamation Circle", class: "fa-solid fa-circle-exclamation" },
    { name: "Warning Triangle", class: "fa-solid fa-triangle-exclamation" },
    { name: "Bell", class: "fa-solid fa-bell" },
    { name: "Bell (Outline)", class: "fa-regular fa-bell" },
    { name: "Bell Slash", class: "fa-solid fa-bell-slash" },
    { name: "Gear / Settings", class: "fa-solid fa-gear" },
    { name: "Gears", class: "fa-solid fa-gears" },
    { name: "Sliders / Controls", class: "fa-solid fa-sliders" },
    { name: "Wrench / Tool", class: "fa-solid fa-wrench" },
    { name: "Screwdriver Wrench", class: "fa-solid fa-screwdriver-wrench" },
    { name: "Magnifier / Search", class: "fa-solid fa-magnifying-glass" },
    { name: "Search Plus", class: "fa-solid fa-magnifying-glass-plus" },
    { name: "Search Minus", class: "fa-solid fa-magnifying-glass-minus" },
    { name: "Eye", class: "fa-solid fa-eye" },
    { name: "Eye Slash", class: "fa-solid fa-eye-slash" },
    { name: "Trash / Delete", class: "fa-solid fa-trash" },
    { name: "Trash Can", class: "fa-solid fa-trash-can" },
    { name: "Pen / Edit", class: "fa-solid fa-pen" },
    { name: "Pen to Square", class: "fa-solid fa-pen-to-square" },
    { name: "Share", class: "fa-solid fa-share" },
    { name: "Share Nodes", class: "fa-solid fa-share-nodes" },
    { name: "Ellipsis / More", class: "fa-solid fa-ellipsis" },
    { name: "Ellipsis Vertical", class: "fa-solid fa-ellipsis-vertical" },
    { name: "Bars / Menu", class: "fa-solid fa-bars" },
    { name: "Grip / Dots", class: "fa-solid fa-grip" },
    { name: "Filter", class: "fa-solid fa-filter" },
    { name: "Sort", class: "fa-solid fa-sort" },
    { name: "Sparkles / AI", class: "fa-solid fa-wand-magic-sparkles" },
    { name: "Bolt / Flash", class: "fa-solid fa-bolt" },
    { name: "Fire", class: "fa-solid fa-fire" },
    { name: "Crown", class: "fa-solid fa-crown" },
    { name: "Award", class: "fa-solid fa-award" },
    { name: "Medal", class: "fa-solid fa-medal" },
    { name: "Trophy", class: "fa-solid fa-trophy" },
    { name: "Certificate", class: "fa-solid fa-certificate" },
    { name: "Ribbon", class: "fa-solid fa-ribbon" },
    { name: "Flag", class: "fa-solid fa-flag" },
    { name: "Bookmark", class: "fa-solid fa-bookmark" },
    { name: "Thumbs Up", class: "fa-solid fa-thumbs-up" },
    { name: "Thumbs Down", class: "fa-solid fa-thumbs-down" },
    { name: "Sun / Light", class: "fa-solid fa-sun" },
    { name: "Moon / Dark", class: "fa-solid fa-moon" },
    { name: "Spinner / Loading", class: "fa-solid fa-spinner fa-spin" },
    { name: "Toggle On", class: "fa-solid fa-toggle-on" },
    { name: "Toggle Off", class: "fa-solid fa-toggle-off" },
  ],

  "Users & Profiles": [
    { name: "User", class: "fa-solid fa-user" },
    { name: "User (Outline)", class: "fa-regular fa-user" },
    { name: "User Plus", class: "fa-solid fa-user-plus" },
    { name: "User Minus", class: "fa-solid fa-user-minus" },
    { name: "User Check", class: "fa-solid fa-user-check" },
    { name: "User Xmark", class: "fa-solid fa-user-xmark" },
    { name: "User Pen", class: "fa-solid fa-user-pen" },
    { name: "User Gear", class: "fa-solid fa-user-gear" },
    { name: "User Shield", class: "fa-solid fa-user-shield" },
    { name: "User Lock", class: "fa-solid fa-user-lock" },
    { name: "User Tie", class: "fa-solid fa-user-tie" },
    { name: "User Graduate", class: "fa-solid fa-user-graduate" },
    { name: "User Doctor", class: "fa-solid fa-user-doctor" },
    { name: "User Astronaut", class: "fa-solid fa-user-astronaut" },
    { name: "User Ninja", class: "fa-solid fa-user-ninja" },
    { name: "Users / Team", class: "fa-solid fa-users" },
    { name: "Users Gear", class: "fa-solid fa-users-gear" },
    { name: "User Group", class: "fa-solid fa-user-group" },
    { name: "Address Book", class: "fa-solid fa-address-book" },
    { name: "Address Card", class: "fa-solid fa-address-card" },
    { name: "Id Badge", class: "fa-solid fa-id-badge" },
    { name: "Id Card", class: "fa-solid fa-id-card" },
    { name: "Circle User", class: "fa-solid fa-circle-user" },
    { name: "People Group", class: "fa-solid fa-people-group" },
    { name: "Handshake", class: "fa-solid fa-handshake" },
    { name: "Hands Holding", class: "fa-solid fa-hands-holding" },
    { name: "Child", class: "fa-solid fa-child" },
    { name: "Person", class: "fa-solid fa-person" },
    { name: "Person Walking", class: "fa-solid fa-person-walking" },
    { name: "Person Running", class: "fa-solid fa-person-running" },
  ],

  "Business & Finance": [
    { name: "Briefcase", class: "fa-solid fa-briefcase" },
    { name: "Building / Office", class: "fa-solid fa-building" },
    { name: "Building Columns", class: "fa-solid fa-building-columns" },
    { name: "City", class: "fa-solid fa-city" },
    { name: "Store / Shop", class: "fa-solid fa-store" },
    { name: "Shop", class: "fa-solid fa-shop" },
    { name: "Cart Shopping", class: "fa-solid fa-cart-shopping" },
    { name: "Cart Plus", class: "fa-solid fa-cart-plus" },
    { name: "Cart Arrow Down", class: "fa-solid fa-cart-arrow-down" },
    { name: "Bag Shopping", class: "fa-solid fa-bag-shopping" },
    { name: "Basket Shopping", class: "fa-solid fa-basket-shopping" },
    { name: "Credit Card", class: "fa-solid fa-credit-card" },
    { name: "Money Bill", class: "fa-solid fa-money-bill" },
    { name: "Money Bill Wave", class: "fa-solid fa-money-bill-wave" },
    { name: "Money Bill 1", class: "fa-solid fa-money-bill-1" },
    { name: "Money Bills", class: "fa-solid fa-money-bills" },
    { name: "Coins", class: "fa-solid fa-coins" },
    { name: "Dollar Sign", class: "fa-solid fa-dollar-sign" },
    { name: "Euro Sign", class: "fa-solid fa-euro-sign" },
    { name: "Sterling Sign", class: "fa-solid fa-sterling-sign" },
    { name: "Indian Rupee Sign", class: "fa-solid fa-indian-rupee-sign" },
    { name: "Yen Sign", class: "fa-solid fa-yen-sign" },
    { name: "Wallet", class: "fa-solid fa-wallet" },
    { name: "Piggy Bank", class: "fa-solid fa-piggy-bank" },
    { name: "Vault", class: "fa-solid fa-vault" },
    { name: "Receipt", class: "fa-solid fa-receipt" },
    { name: "Invoice / File Invoice", class: "fa-solid fa-file-invoice" },
    { name: "File Invoice Dollar", class: "fa-solid fa-file-invoice-dollar" },
    { name: "Tag / Price", class: "fa-solid fa-tag" },
    { name: "Tags / Labels", class: "fa-solid fa-tags" },
    { name: "Percent / Discount", class: "fa-solid fa-percent" },
    { name: "Chart Line / Growth", class: "fa-solid fa-chart-line" },
    { name: "Chart Simple / Bar", class: "fa-solid fa-chart-simple" },
    { name: "Chart Column", class: "fa-solid fa-chart-column" },
    { name: "Chart Pie", class: "fa-solid fa-chart-pie" },
    { name: "Chart Area", class: "fa-solid fa-chart-area" },
    { name: "Chart Gantt", class: "fa-solid fa-chart-gantt" },
    { name: "Scale Balanced / Legal", class: "fa-solid fa-scale-balanced" },
    { name: "Gavel", class: "fa-solid fa-gavel" },
    { name: "Hand Holding Dollar", class: "fa-solid fa-hand-holding-dollar" },
    { name: "Bullseye / Target", class: "fa-solid fa-bullseye" },
    { name: "Lightbulb / Idea", class: "fa-solid fa-lightbulb" },
    { name: "Rocket / Launch", class: "fa-solid fa-rocket" },
    { name: "Sitemap", class: "fa-solid fa-sitemap" },
    { name: "Calculator", class: "fa-solid fa-calculator" },
  ],

  "Communication & Contact": [
    { name: "Envelope / Mail", class: "fa-solid fa-envelope" },
    { name: "Envelope Open", class: "fa-solid fa-envelope-open" },
    { name: "Envelope Open Text", class: "fa-solid fa-envelope-open-text" },
    { name: "Envelopes Bulk", class: "fa-solid fa-envelopes-bulk" },
    { name: "Inbox", class: "fa-solid fa-inbox" },
    { name: "Paper Plane / Send", class: "fa-solid fa-paper-plane" },
    { name: "Phone", class: "fa-solid fa-phone" },
    { name: "Phone Flip", class: "fa-solid fa-phone-flip" },
    { name: "Phone Volume", class: "fa-solid fa-phone-volume" },
    { name: "Phone Slash", class: "fa-solid fa-phone-slash" },
    { name: "Mobile Screen", class: "fa-solid fa-mobile-screen" },
    { name: "Mobile", class: "fa-solid fa-mobile" },
    { name: "Tablet Screen", class: "fa-solid fa-tablet-screen-button" },
    { name: "Comment / Message", class: "fa-solid fa-comment" },
    { name: "Comment (Outline)", class: "fa-regular fa-comment" },
    { name: "Comment Dots", class: "fa-solid fa-comment-dots" },
    { name: "Comments / Chat", class: "fa-solid fa-comments" },
    { name: "Comment Medical", class: "fa-solid fa-comment-medical" },
    { name: "Headset / Support", class: "fa-solid fa-headset" },
    { name: "Bullhorn / Megaphone", class: "fa-solid fa-bullhorn" },
    { name: "Walkie Talkie", class: "fa-solid fa-walkie-talkie" },
    { name: "Location Dot / Pin", class: "fa-solid fa-location-dot" },
    { name: "Location Pin", class: "fa-solid fa-location-pin" },
    { name: "Location Crosshairs", class: "fa-solid fa-location-crosshairs" },
    { name: "Location Arrow", class: "fa-solid fa-location-arrow" },
    { name: "Map", class: "fa-solid fa-map" },
    { name: "Map Pin", class: "fa-solid fa-map-pin" },
    { name: "Map Location", class: "fa-solid fa-map-location" },
    { name: "Map Location Dot", class: "fa-solid fa-map-location-dot" },
    { name: "Compass", class: "fa-solid fa-compass" },
    { name: "Globe / Web", class: "fa-solid fa-globe" },
    { name: "Calendar", class: "fa-solid fa-calendar" },
    { name: "Calendar Days", class: "fa-solid fa-calendar-days" },
    { name: "Calendar Check", class: "fa-solid fa-calendar-check" },
    { name: "Calendar Plus", class: "fa-solid fa-calendar-plus" },
    { name: "Clock / Time", class: "fa-solid fa-clock" },
    { name: "Clock Rotate Left", class: "fa-solid fa-clock-rotate-left" },
    { name: "Stopwatch", class: "fa-solid fa-stopwatch" },
    { name: "Hourglass", class: "fa-solid fa-hourglass" },
    { name: "At Sign", class: "fa-solid fa-at" },
    { name: "Hashtag", class: "fa-solid fa-hashtag" },
    { name: "RSS", class: "fa-solid fa-rss" },
  ],

  "Technology & Code": [
    { name: "Laptop", class: "fa-solid fa-laptop" },
    { name: "Laptop Code", class: "fa-solid fa-laptop-code" },
    { name: "Desktop", class: "fa-solid fa-desktop" },
    { name: "Computer", class: "fa-solid fa-computer" },
    { name: "Server", class: "fa-solid fa-server" },
    { name: "Database", class: "fa-solid fa-database" },
    { name: "Hard Drive", class: "fa-solid fa-hard-drive" },
    { name: "Memory / RAM", class: "fa-solid fa-memory" },
    { name: "Microchip / CPU", class: "fa-solid fa-microchip" },
    { name: "Code", class: "fa-solid fa-code" },
    { name: "Code Branch", class: "fa-solid fa-code-branch" },
    { name: "Code Commit", class: "fa-solid fa-code-commit" },
    { name: "Code Pull Request", class: "fa-solid fa-code-pull-request" },
    { name: "Code Merge", class: "fa-solid fa-code-merge" },
    { name: "Code Fork", class: "fa-solid fa-code-fork" },
    { name: "Code Compare", class: "fa-solid fa-code-compare" },
    { name: "Terminal", class: "fa-solid fa-terminal" },
    { name: "Window Restore", class: "fa-solid fa-window-restore" },
    { name: "Window Maximize", class: "fa-solid fa-window-maximize" },
    { name: "Window Minimize", class: "fa-solid fa-window-minimize" },
    { name: "Bug", class: "fa-solid fa-bug" },
    { name: "Bug Slash", class: "fa-solid fa-bug-slash" },
    { name: "Cloud", class: "fa-solid fa-cloud" },
    { name: "Cloud Arrow Up", class: "fa-solid fa-cloud-arrow-up" },
    { name: "Cloud Arrow Down", class: "fa-solid fa-cloud-arrow-down" },
    { name: "Wifi", class: "fa-solid fa-wifi" },
    { name: "Ethernet", class: "fa-solid fa-ethernet" },
    { name: "Network Wired", class: "fa-solid fa-network-wired" },
    { name: "Signal", class: "fa-solid fa-signal" },
    { name: "Robot", class: "fa-solid fa-robot" },
    { name: "Brain", class: "fa-solid fa-brain" },
    { name: "Fingerprint", class: "fa-solid fa-fingerprint" },
    { name: "Qrcode", class: "fa-solid fa-qrcode" },
    { name: "Barcode", class: "fa-solid fa-barcode" },
    { name: "Battery Full", class: "fa-solid fa-battery-full" },
    { name: "Plug / Power", class: "fa-solid fa-plug" },
    { name: "Power Off", class: "fa-solid fa-power-off" },
    { name: "Link", class: "fa-solid fa-link" },
    { name: "Link Slash", class: "fa-solid fa-link-slash" },
    { name: "Paperclip", class: "fa-solid fa-paperclip" },
  ],

  "Media & Audio/Video": [
    { name: "Play", class: "fa-solid fa-play" },
    { name: "Pause", class: "fa-solid fa-pause" },
    { name: "Stop", class: "fa-solid fa-stop" },
    { name: "Forward", class: "fa-solid fa-forward" },
    { name: "Backward", class: "fa-solid fa-backward" },
    { name: "Forward Step", class: "fa-solid fa-forward-step" },
    { name: "Backward Step", class: "fa-solid fa-backward-step" },
    { name: "Circle Play", class: "fa-solid fa-circle-play" },
    { name: "Circle Pause", class: "fa-solid fa-circle-pause" },
    { name: "Circle Stop", class: "fa-solid fa-circle-stop" },
    { name: "Video / Camera", class: "fa-solid fa-video" },
    { name: "Video Slash", class: "fa-solid fa-video-slash" },
    { name: "Camera", class: "fa-solid fa-camera" },
    { name: "Camera Retro", class: "fa-solid fa-camera-retro" },
    { name: "Image / Picture", class: "fa-solid fa-image" },
    { name: "Images / Gallery", class: "fa-solid fa-images" },
    { name: "Photo Film", class: "fa-solid fa-photo-film" },
    { name: "Film", class: "fa-solid fa-film" },
    { name: "Clapperboard", class: "fa-solid fa-clapperboard" },
    { name: "Music", class: "fa-solid fa-music" },
    { name: "Headphones", class: "fa-solid fa-headphones" },
    { name: "Microphone", class: "fa-solid fa-microphone" },
    { name: "Microphone Slash", class: "fa-solid fa-microphone-slash" },
    { name: "Volume High", class: "fa-solid fa-volume-high" },
    { name: "Volume Low", class: "fa-solid fa-volume-low" },
    { name: "Volume Off", class: "fa-solid fa-volume-off" },
    { name: "Volume Xmark", class: "fa-solid fa-volume-xmark" },
    { name: "Radio", class: "fa-solid fa-radio" },
    { name: "Podcast", class: "fa-solid fa-podcast" },
    { name: "Broadcast Tower", class: "fa-solid fa-tower-broadcast" },
    { name: "Tv / Television", class: "fa-solid fa-tv" },
    { name: "Gamepad", class: "fa-solid fa-gamepad" },
  ],

  "Security & Privacy": [
    { name: "Lock", class: "fa-solid fa-lock" },
    { name: "Lock Open", class: "fa-solid fa-lock-open" },
    { name: "Key", class: "fa-solid fa-key" },
    { name: "Shield", class: "fa-solid fa-shield" },
    { name: "Shield Halved", class: "fa-solid fa-shield-halved" },
    { name: "Shield Heart", class: "fa-solid fa-shield-heart" },
    { name: "Shield Virus", class: "fa-solid fa-shield-virus" },
    { name: "Shield Cat", class: "fa-solid fa-shield-cat" },
    { name: "User Secret / Incognito", class: "fa-solid fa-user-secret" },
    { name: "Passport", class: "fa-solid fa-passport" },
    { name: "File Shield", class: "fa-solid fa-file-shield" },
    { name: "Lock (Outline)", class: "fa-regular fa-lock" },
  ],

  "Files & Documents": [
    { name: "File", class: "fa-solid fa-file" },
    { name: "File (Outline)", class: "fa-regular fa-file" },
    { name: "File Lines / Document", class: "fa-solid fa-file-lines" },
    { name: "File Code", class: "fa-solid fa-file-code" },
    { name: "File PDF", class: "fa-solid fa-file-pdf" },
    { name: "File Image", class: "fa-solid fa-file-image" },
    { name: "File Video", class: "fa-solid fa-file-video" },
    { name: "File Audio", class: "fa-solid fa-file-audio" },
    { name: "File Word", class: "fa-solid fa-file-word" },
    { name: "File Excel", class: "fa-solid fa-file-excel" },
    { name: "File Powerpoint", class: "fa-solid fa-file-powerpoint" },
    { name: "File Zipper / Archive", class: "fa-solid fa-file-zipper" },
    { name: "File CSV", class: "fa-solid fa-file-csv" },
    { name: "File Signature", class: "fa-solid fa-file-signature" },
    { name: "File Contract", class: "fa-solid fa-file-contract" },
    { name: "File Export", class: "fa-solid fa-file-export" },
    { name: "File Import", class: "fa-solid fa-file-import" },
    { name: "Folder", class: "fa-solid fa-folder" },
    { name: "Folder Open", class: "fa-solid fa-folder-open" },
    { name: "Folder Plus", class: "fa-solid fa-folder-plus" },
    { name: "Folder Minus", class: "fa-solid fa-folder-minus" },
    { name: "Folder Tree", class: "fa-solid fa-folder-tree" },
    { name: "Box / Package", class: "fa-solid fa-box" },
    { name: "Boxes / Stack", class: "fa-solid fa-boxes-stacked" },
    { name: "Boxes Packing", class: "fa-solid fa-boxes-packing" },
    { name: "Clipboard", class: "fa-solid fa-clipboard" },
    { name: "Clipboard Check", class: "fa-solid fa-clipboard-check" },
    { name: "Clipboard List", class: "fa-solid fa-clipboard-list" },
    { name: "Newspaper", class: "fa-solid fa-newspaper" },
    { name: "Book", class: "fa-solid fa-book" },
    { name: "Book Open", class: "fa-solid fa-book-open" },
    { name: "Bookmark", class: "fa-solid fa-bookmark" },
  ],

  "Arrows & Navigation": [
    { name: "Arrow Right", class: "fa-solid fa-arrow-right" },
    { name: "Arrow Left", class: "fa-solid fa-arrow-left" },
    { name: "Arrow Up", class: "fa-solid fa-arrow-up" },
    { name: "Arrow Down", class: "fa-solid fa-arrow-down" },
    { name: "Arrow Up Right", class: "fa-solid fa-arrow-up-right-from-square" },
    { name: "Arrow Down Left", class: "fa-solid fa-arrow-down-left-and-up-right-to-center" },
    { name: "Chevron Right", class: "fa-solid fa-chevron-right" },
    { name: "Chevron Left", class: "fa-solid fa-chevron-left" },
    { name: "Chevron Up", class: "fa-solid fa-chevron-up" },
    { name: "Chevron Down", class: "fa-solid fa-chevron-down" },
    { name: "Angle Right", class: "fa-solid fa-angle-right" },
    { name: "Angle Left", class: "fa-solid fa-angle-left" },
    { name: "Angle Up", class: "fa-solid fa-angle-up" },
    { name: "Angle Down", class: "fa-solid fa-angle-down" },
    { name: "Angles Right", class: "fa-solid fa-angles-right" },
    { name: "Angles Left", class: "fa-solid fa-angles-left" },
    { name: "Angles Up", class: "fa-solid fa-angles-up" },
    { name: "Angles Down", class: "fa-solid fa-angles-down" },
    { name: "Caret Right", class: "fa-solid fa-caret-right" },
    { name: "Caret Left", class: "fa-solid fa-caret-left" },
    { name: "Caret Up", class: "fa-solid fa-caret-up" },
    { name: "Caret Down", class: "fa-solid fa-caret-down" },
    { name: "Circle Arrow Right", class: "fa-solid fa-circle-arrow-right" },
    { name: "Circle Arrow Left", class: "fa-solid fa-circle-arrow-left" },
    { name: "Circle Arrow Up", class: "fa-solid fa-circle-arrow-up" },
    { name: "Circle Arrow Down", class: "fa-solid fa-circle-arrow-down" },
    { name: "Circle Chevron Right", class: "fa-solid fa-circle-chevron-right" },
    { name: "Circle Chevron Left", class: "fa-solid fa-circle-chevron-left" },
    { name: "Arrows Rotate / Refresh", class: "fa-solid fa-arrows-rotate" },
    { name: "Rotate Right", class: "fa-solid fa-rotate-right" },
    { name: "Rotate Left", class: "fa-solid fa-rotate-left" },
    { name: "Arrow Trend Up", class: "fa-solid fa-arrow-trend-up" },
    { name: "Arrow Trend Down", class: "fa-solid fa-arrow-trend-down" },
    { name: "Download", class: "fa-solid fa-download" },
    { name: "Upload", class: "fa-solid fa-upload" },
    { name: "Right To Bracket / Login", class: "fa-solid fa-right-to-bracket" },
    { name: "Right From Bracket / Logout", class: "fa-solid fa-right-from-bracket" },
  ],

  "Social & Brand Icons": [
    { name: "Twitter / X", class: "fa-brands fa-x-twitter" },
    { name: "Twitter (Classic)", class: "fa-brands fa-twitter" },
    { name: "Facebook", class: "fa-brands fa-facebook" },
    { name: "Facebook F", class: "fa-brands fa-facebook-f" },
    { name: "Instagram", class: "fa-brands fa-instagram" },
    { name: "LinkedIn", class: "fa-brands fa-linkedin" },
    { name: "LinkedIn In", class: "fa-brands fa-linkedin-in" },
    { name: "YouTube", class: "fa-brands fa-youtube" },
    { name: "TikTok", class: "fa-brands fa-tiktok" },
    { name: "Pinterest", class: "fa-brands fa-pinterest" },
    { name: "Pinterest P", class: "fa-brands fa-pinterest-p" },
    { name: "Snapchat", class: "fa-brands fa-snapchat" },
    { name: "WhatsApp", class: "fa-brands fa-whatsapp" },
    { name: "Telegram", class: "fa-brands fa-telegram" },
    { name: "Discord", class: "fa-brands fa-discord" },
    { name: "Slack", class: "fa-brands fa-slack" },
    { name: "Reddit", class: "fa-brands fa-reddit" },
    { name: "Reddit Alien", class: "fa-brands fa-reddit-alien" },
    { name: "Twitch", class: "fa-brands fa-twitch" },
    { name: "GitHub", class: "fa-brands fa-github" },
    { name: "GitLab", class: "fa-brands fa-gitlab" },
    { name: "Bitbucket", class: "fa-brands fa-bitbucket" },
    { name: "Stack Overflow", class: "fa-brands fa-stack-overflow" },
    { name: "Medium", class: "fa-brands fa-medium" },
    { name: "Dev.to", class: "fa-brands fa-dev" },
    { name: "Hashnode", class: "fa-brands fa-hashnode" },
    { name: "Dribbble", class: "fa-brands fa-dribbble" },
    { name: "Behance", class: "fa-brands fa-behance" },
    { name: "Figma", class: "fa-brands fa-figma" },
    { name: "Google", class: "fa-brands fa-google" },
    { name: "Google Play", class: "fa-brands fa-google-play" },
    { name: "Google Drive", class: "fa-brands fa-google-drive" },
    { name: "Apple", class: "fa-brands fa-apple" },
    { name: "App Store", class: "fa-brands fa-app-store" },
    { name: "Microsoft", class: "fa-brands fa-microsoft" },
    { name: "Windows", class: "fa-brands fa-windows" },
    { name: "Amazon", class: "fa-brands fa-amazon" },
    { name: "Stripe", class: "fa-brands fa-stripe" },
    { name: "Stripe S", class: "fa-brands fa-stripe-s" },
    { name: "PayPal", class: "fa-brands fa-paypal" },
    { name: "Shopify", class: "fa-brands fa-shopify" },
    { name: "WordPress", class: "fa-brands fa-wordpress" },
    { name: "Spotify", class: "fa-brands fa-spotify" },
    { name: "SoundCloud", class: "fa-brands fa-soundcloud" },
    { name: "Steam", class: "fa-brands fa-steam" },
    { name: "PlayStation", class: "fa-brands fa-playstation" },
    { name: "Xbox", class: "fa-brands fa-xbox" },
    { name: "Uber", class: "fa-brands fa-uber" },
    { name: "Airbnb", class: "fa-brands fa-airbnb" },
    { name: "HubSpot", class: "fa-brands fa-hubspot" },
    { name: "Mailchimp", class: "fa-brands fa-mailchimp" },
    { name: "Product Hunt", class: "fa-brands fa-product-hunt" },
    { name: "Patreon", class: "fa-brands fa-patreon" },
    { name: "Kickstarter", class: "fa-brands fa-kickstarter" },
  ],

  "Medical & Health": [
    { name: "Heart Pulse", class: "fa-solid fa-heart-pulse" },
    { name: "Stethoscope", class: "fa-solid fa-stethoscope" },
    { name: "Hospital", class: "fa-solid fa-hospital" },
    { name: "Pills", class: "fa-solid fa-pills" },
    { name: "Prescription Bottle", class: "fa-solid fa-prescription-bottle" },
    { name: "Syringe", class: "fa-solid fa-syringe" },
    { name: "Bandage", class: "fa-solid fa-bandage" },
    { name: "First Aid Kit", class: "fa-solid fa-kit-medical" },
    { name: "Virus", class: "fa-solid fa-virus" },
    { name: "Lungs", class: "fa-solid fa-lungs" },
    { name: "Brain", class: "fa-solid fa-brain" },
    { name: "Eye Dropper", class: "fa-solid fa-eye-dropper" },
    { name: "Wheelchair", class: "fa-solid fa-wheelchair" },
    { name: "Dumbbell / Fitness", class: "fa-solid fa-dumbbell" },
    { name: "Apple Whole / Nutrition", class: "fa-solid fa-apple-whole" },
  ],

  "Travel & Places": [
    { name: "Plane", class: "fa-solid fa-plane" },
    { name: "Plane Departure", class: "fa-solid fa-plane-departure" },
    { name: "Plane Arrival", class: "fa-solid fa-plane-arrival" },
    { name: "Car", class: "fa-solid fa-car" },
    { name: "Bus", class: "fa-solid fa-bus" },
    { name: "Train", class: "fa-solid fa-train" },
    { name: "Bicycle", class: "fa-solid fa-bicycle" },
    { name: "Motorcycle", class: "fa-solid fa-motorcycle" },
    { name: "Ship / Boat", class: "fa-solid fa-ship" },
    { name: "Hotel", class: "fa-solid fa-hotel" },
    { name: "Bed", class: "fa-solid fa-bed" },
    { name: "Luggage / Suitcase", class: "fa-solid fa-suitcase" },
    { name: "Umbrella Beach", class: "fa-solid fa-umbrella-beach" },
    { name: "Mountain", class: "fa-solid fa-mountain" },
    { name: "Tree", class: "fa-solid fa-tree" },
    { name: "Utensils / Restaurant", class: "fa-solid fa-utensils" },
    { name: "Mug Saucer / Coffee", class: "fa-solid fa-mug-saucer" },
    { name: "Wine Glass / Bar", class: "fa-solid fa-wine-glass" },
    { name: "Burger / Food", class: "fa-solid fa-burger" },
    { name: "Pizza Slice", class: "fa-solid fa-pizza-slice" },
    { name: "Gas Pump", class: "fa-solid fa-gas-pump" },
  ],
};
