/**
 * sanitizeRichHtml.js
 *
 * A shared server-side HTML sanitizer for rich-text content (blog posts, KB articles).
 * Uses sanitize-html to strip dangerous tags/attributes while preserving safe formatting.
 *
 * Only call this on HTML generated by a rich-text editor (TipTap, Quill, etc.)
 * before persisting to the database or serving it publicly.
 */

import sanitizeHtml from "sanitize-html";

/** Tags allowed in rich-text editor content */
const ALLOWED_TAGS = [
  // Headings
  "h1", "h2", "h3", "h4", "h5", "h6",
  // Text formatting
  "p", "br", "hr", "blockquote", "pre", "code",
  "strong", "b", "em", "i", "u", "s", "strike", "del",
  "sup", "sub", "mark",
  // Lists
  "ul", "ol", "li",
  // Tables
  "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption",
  // Media & links
  "a", "img", "figure", "figcaption",
  // Layout
  "div", "span",
];

/** Safe attributes allowed per tag */
const ALLOWED_ATTRIBUTES = {
  a: ["href", "title", "target", "rel"],
  img: ["src", "alt", "title", "width", "height", "loading"],
  td: ["colspan", "rowspan"],
  th: ["colspan", "rowspan", "scope"],
  table: ["border", "cellpadding", "cellspacing"],
  "*": ["class", "id"],
};

const SANITIZE_OPTIONS = {
  allowedTags: ALLOWED_TAGS,
  allowedAttributes: ALLOWED_ATTRIBUTES,
  allowedSchemes: ["http", "https", "mailto", "tel"],
  allowedSchemesByTag: {
    img: ["http", "https", "data"],
  },
  // Force external links to open safely
  transformTags: {
    a: (tagName, attribs) => ({
      tagName,
      attribs: {
        ...attribs,
        // Only allow safe protocols in hrefs
        href: /^(https?:\/\/|mailto:|tel:|\/|#)/.test(attribs.href ?? "")
          ? attribs.href
          : "#",
        // All external links get noopener noreferrer
        rel: "noopener noreferrer",
      },
    }),
  },
};

/**
 * Sanitize an HTML string from a rich-text editor.
 * @param {string} html - Raw HTML from user input
 * @returns {string} - Sanitized HTML safe to store and render
 */
export function sanitizeRichHtml(html) {
  if (typeof html !== "string") return "";
  return sanitizeHtml(html, SANITIZE_OPTIONS);
}
