/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundCancellationPolicyRouteImport } from './routes/refund-cancellation-policy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyPasswordResetRouteImport } from './routes/verify-password-reset'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminKbRouteImport } from './routes/admin.kb'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminWebsitesRouteImport } from './routes/admin.websites'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as TenantActivityRouteImport } from './routes/tenant.activity'
import { Route as TenantAnalyticsRouteImport } from './routes/tenant.analytics'
import { Route as TenantBillingRouteImport } from './routes/tenant.billing'
import { Route as TenantBlogRouteImport } from './routes/tenant.blog'
import { Route as TenantBusinessRouteImport } from './routes/tenant.business'
import { Route as TenantDomainsRouteImport } from './routes/tenant.domains'
import { Route as TenantFormsRouteImport } from './routes/tenant.forms'
import { Route as TenantKbRouteImport } from './routes/tenant.kb'
import { Route as TenantMediaRouteImport } from './routes/tenant.media'
import { Route as TenantPagesRouteImport } from './routes/tenant.pages'
import { Route as TenantSeoRouteImport } from './routes/tenant.seo'
import { Route as TenantSettingsRouteImport } from './routes/tenant.settings'
import { Route as TenantSubscriptionRouteImport } from './routes/tenant.subscription'
import { Route as TenantSupportRouteImport } from './routes/tenant.support'
import { Route as TenantWebsitesRouteImport } from './routes/tenant.websites'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin.tenants.index'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'
import { Route as TenantBuilderIdRouteImport } from './routes/tenant_.builder.$id'
import { Route as AdminWebsitesIdBuilderRouteImport } from './routes/admin.websites_.$id.builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundCancellationPolicyRoute =
  RefundCancellationPolicyRouteImport.update({
    id: '/refund-cancellation-policy',
    path: '/refund-cancellation-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPasswordResetRoute = VerifyPasswordResetRouteImport.update({
  id: '/verify-password-reset',
  path: '/verify-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKbRoute = AdminKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsitesRoute = AdminWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const TenantActivityRoute = TenantActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAnalyticsRoute = TenantAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBillingRoute = TenantBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBlogRoute = TenantBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBusinessRoute = TenantBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => TenantRoute,
} as any)
const TenantDomainsRoute = TenantDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => TenantRoute,
} as any)
const TenantFormsRoute = TenantFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => TenantRoute,
} as any)
const TenantKbRoute = TenantKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMediaRoute = TenantMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPagesRoute = TenantPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSeoRoute = TenantSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSettingsRoute = TenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSubscriptionRoute = TenantSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSupportRoute = TenantSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => TenantRoute,
} as any)
const TenantWebsitesRoute = TenantWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => TenantRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => AdminRoute,
} as any)
const TenantBuilderIdRoute = TenantBuilderIdRouteImport.update({
  id: '/tenant_/builder/$id',
  path: '/tenant/builder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsitesIdBuilderRoute = AdminWebsitesIdBuilderRouteImport.update({
  id: '/websites_/$id/builder',
  path: '/websites/$id/builder',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof TemplatesRoute
  '/tenant': typeof TenantRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-password-reset': typeof VerifyPasswordResetRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/kb': typeof AdminKbRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/websites': typeof AdminWebsitesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tenant/activity': typeof TenantActivityRoute
  '/tenant/analytics': typeof TenantAnalyticsRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/blog': typeof TenantBlogRoute
  '/tenant/business': typeof TenantBusinessRoute
  '/tenant/domains': typeof TenantDomainsRoute
  '/tenant/forms': typeof TenantFormsRoute
  '/tenant/kb': typeof TenantKbRoute
  '/tenant/media': typeof TenantMediaRoute
  '/tenant/pages': typeof TenantPagesRoute
  '/tenant/seo': typeof TenantSeoRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/subscription': typeof TenantSubscriptionRoute
  '/tenant/support': typeof TenantSupportRoute
  '/tenant/websites': typeof TenantWebsitesRoute
  '/blog/': typeof BlogIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/tenant/builder/$id': typeof TenantBuilderIdRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/admin/websites/$id/builder': typeof AdminWebsitesIdBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof TemplatesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-password-reset': typeof VerifyPasswordResetRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/kb': typeof AdminKbRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/websites': typeof AdminWebsitesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tenant/activity': typeof TenantActivityRoute
  '/tenant/analytics': typeof TenantAnalyticsRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/blog': typeof TenantBlogRoute
  '/tenant/business': typeof TenantBusinessRoute
  '/tenant/domains': typeof TenantDomainsRoute
  '/tenant/forms': typeof TenantFormsRoute
  '/tenant/kb': typeof TenantKbRoute
  '/tenant/media': typeof TenantMediaRoute
  '/tenant/pages': typeof TenantPagesRoute
  '/tenant/seo': typeof TenantSeoRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/subscription': typeof TenantSubscriptionRoute
  '/tenant/support': typeof TenantSupportRoute
  '/tenant/websites': typeof TenantWebsitesRoute
  '/blog': typeof BlogIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/tenant/builder/$id': typeof TenantBuilderIdRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/admin/websites/$id/builder': typeof AdminWebsitesIdBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof TemplatesRoute
  '/tenant': typeof TenantRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-password-reset': typeof VerifyPasswordResetRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/kb': typeof AdminKbRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/websites': typeof AdminWebsitesRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/tenant/activity': typeof TenantActivityRoute
  '/tenant/analytics': typeof TenantAnalyticsRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/blog': typeof TenantBlogRoute
  '/tenant/business': typeof TenantBusinessRoute
  '/tenant/domains': typeof TenantDomainsRoute
  '/tenant/forms': typeof TenantFormsRoute
  '/tenant/kb': typeof TenantKbRoute
  '/tenant/media': typeof TenantMediaRoute
  '/tenant/pages': typeof TenantPagesRoute
  '/tenant/seo': typeof TenantSeoRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/subscription': typeof TenantSubscriptionRoute
  '/tenant/support': typeof TenantSupportRoute
  '/tenant/websites': typeof TenantWebsitesRoute
  '/blog/': typeof BlogIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/tenant_/builder/$id': typeof TenantBuilderIdRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/admin/websites_/$id/builder': typeof AdminWebsitesIdBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/contact'
    | '/create-account'
    | '/forgot-password'
    | '/help'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/sign-in'
    | '/templates'
    | '/tenant'
    | '/terms-and-conditions'
    | '/verify-email'
    | '/verify-password-reset'
    | '/admin/activity-logs'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/domains'
    | '/admin/email-templates'
    | '/admin/kb'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/testimonials'
    | '/admin/websites'
    | '/blog/$slug'
    | '/tenant/activity'
    | '/tenant/analytics'
    | '/tenant/billing'
    | '/tenant/blog'
    | '/tenant/business'
    | '/tenant/domains'
    | '/tenant/forms'
    | '/tenant/kb'
    | '/tenant/media'
    | '/tenant/pages'
    | '/tenant/seo'
    | '/tenant/settings'
    | '/tenant/subscription'
    | '/tenant/support'
    | '/tenant/websites'
    | '/blog/'
    | '/tenant/'
    | '/admin/tenants/$id'
    | '/tenant/builder/$id'
    | '/admin/tenants/'
    | '/admin/websites/$id/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/contact'
    | '/create-account'
    | '/forgot-password'
    | '/help'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/sign-in'
    | '/templates'
    | '/terms-and-conditions'
    | '/verify-email'
    | '/verify-password-reset'
    | '/admin/activity-logs'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/domains'
    | '/admin/email-templates'
    | '/admin/kb'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/testimonials'
    | '/admin/websites'
    | '/blog/$slug'
    | '/tenant/activity'
    | '/tenant/analytics'
    | '/tenant/billing'
    | '/tenant/blog'
    | '/tenant/business'
    | '/tenant/domains'
    | '/tenant/forms'
    | '/tenant/kb'
    | '/tenant/media'
    | '/tenant/pages'
    | '/tenant/seo'
    | '/tenant/settings'
    | '/tenant/subscription'
    | '/tenant/support'
    | '/tenant/websites'
    | '/blog'
    | '/tenant'
    | '/admin/tenants/$id'
    | '/tenant/builder/$id'
    | '/admin/tenants'
    | '/admin/websites/$id/builder'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/contact'
    | '/create-account'
    | '/forgot-password'
    | '/help'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/sign-in'
    | '/templates'
    | '/tenant'
    | '/terms-and-conditions'
    | '/verify-email'
    | '/verify-password-reset'
    | '/admin/activity-logs'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/domains'
    | '/admin/email-templates'
    | '/admin/kb'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/testimonials'
    | '/admin/websites'
    | '/blog_/$slug'
    | '/tenant/activity'
    | '/tenant/analytics'
    | '/tenant/billing'
    | '/tenant/blog'
    | '/tenant/business'
    | '/tenant/domains'
    | '/tenant/forms'
    | '/tenant/kb'
    | '/tenant/media'
    | '/tenant/pages'
    | '/tenant/seo'
    | '/tenant/settings'
    | '/tenant/subscription'
    | '/tenant/support'
    | '/tenant/websites'
    | '/blog/'
    | '/tenant/'
    | '/admin/tenants/$id'
    | '/tenant_/builder/$id'
    | '/admin/tenants/'
    | '/admin/websites_/$id/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CreateAccountRoute: typeof CreateAccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundCancellationPolicyRoute: typeof RefundCancellationPolicyRoute
  SignInRoute: typeof SignInRoute
  TemplatesRoute: typeof TemplatesRoute
  TenantRoute: typeof TenantRouteWithChildren
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyPasswordResetRoute: typeof VerifyPasswordResetRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TenantBuilderIdRoute: typeof TenantBuilderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-cancellation-policy': {
      id: '/refund-cancellation-policy'
      path: '/refund-cancellation-policy'
      fullPath: '/refund-cancellation-policy'
      preLoaderRoute: typeof RefundCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-password-reset': {
      id: '/verify-password-reset'
      path: '/verify-password-reset'
      fullPath: '/verify-password-reset'
      preLoaderRoute: typeof VerifyPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kb': {
      id: '/admin/kb'
      path: '/kb'
      fullPath: '/admin/kb'
      preLoaderRoute: typeof AdminKbRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/websites': {
      id: '/admin/websites'
      path: '/websites'
      fullPath: '/admin/websites'
      preLoaderRoute: typeof AdminWebsitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/activity': {
      id: '/tenant/activity'
      path: '/activity'
      fullPath: '/tenant/activity'
      preLoaderRoute: typeof TenantActivityRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/analytics': {
      id: '/tenant/analytics'
      path: '/analytics'
      fullPath: '/tenant/analytics'
      preLoaderRoute: typeof TenantAnalyticsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/billing': {
      id: '/tenant/billing'
      path: '/billing'
      fullPath: '/tenant/billing'
      preLoaderRoute: typeof TenantBillingRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/blog': {
      id: '/tenant/blog'
      path: '/blog'
      fullPath: '/tenant/blog'
      preLoaderRoute: typeof TenantBlogRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/business': {
      id: '/tenant/business'
      path: '/business'
      fullPath: '/tenant/business'
      preLoaderRoute: typeof TenantBusinessRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/domains': {
      id: '/tenant/domains'
      path: '/domains'
      fullPath: '/tenant/domains'
      preLoaderRoute: typeof TenantDomainsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/forms': {
      id: '/tenant/forms'
      path: '/forms'
      fullPath: '/tenant/forms'
      preLoaderRoute: typeof TenantFormsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/kb': {
      id: '/tenant/kb'
      path: '/kb'
      fullPath: '/tenant/kb'
      preLoaderRoute: typeof TenantKbRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/media': {
      id: '/tenant/media'
      path: '/media'
      fullPath: '/tenant/media'
      preLoaderRoute: typeof TenantMediaRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/pages': {
      id: '/tenant/pages'
      path: '/pages'
      fullPath: '/tenant/pages'
      preLoaderRoute: typeof TenantPagesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/seo': {
      id: '/tenant/seo'
      path: '/seo'
      fullPath: '/tenant/seo'
      preLoaderRoute: typeof TenantSeoRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/settings': {
      id: '/tenant/settings'
      path: '/settings'
      fullPath: '/tenant/settings'
      preLoaderRoute: typeof TenantSettingsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/subscription': {
      id: '/tenant/subscription'
      path: '/subscription'
      fullPath: '/tenant/subscription'
      preLoaderRoute: typeof TenantSubscriptionRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/support': {
      id: '/tenant/support'
      path: '/support'
      fullPath: '/tenant/support'
      preLoaderRoute: typeof TenantSupportRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/websites': {
      id: '/tenant/websites'
      path: '/websites'
      fullPath: '/tenant/websites'
      preLoaderRoute: typeof TenantWebsitesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant_/builder/$id': {
      id: '/tenant_/builder/$id'
      path: '/tenant/builder/$id'
      fullPath: '/tenant/builder/$id'
      preLoaderRoute: typeof TenantBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/websites_/$id/builder': {
      id: '/admin/websites_/$id/builder'
      path: '/websites/$id/builder'
      fullPath: '/admin/websites/$id/builder'
      preLoaderRoute: typeof AdminWebsitesIdBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminKbRoute: typeof AdminKbRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminWebsitesRoute: typeof AdminWebsitesRoute
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
  AdminWebsitesIdBuilderRoute: typeof AdminWebsitesIdBuilderRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminKbRoute: AdminKbRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminWebsitesRoute: AdminWebsitesRoute,
  AdminTenantsIdRoute: AdminTenantsIdRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
  AdminWebsitesIdBuilderRoute: AdminWebsitesIdBuilderRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TenantRouteChildren {
  TenantActivityRoute: typeof TenantActivityRoute
  TenantAnalyticsRoute: typeof TenantAnalyticsRoute
  TenantBillingRoute: typeof TenantBillingRoute
  TenantBlogRoute: typeof TenantBlogRoute
  TenantBusinessRoute: typeof TenantBusinessRoute
  TenantDomainsRoute: typeof TenantDomainsRoute
  TenantFormsRoute: typeof TenantFormsRoute
  TenantKbRoute: typeof TenantKbRoute
  TenantMediaRoute: typeof TenantMediaRoute
  TenantPagesRoute: typeof TenantPagesRoute
  TenantSeoRoute: typeof TenantSeoRoute
  TenantSettingsRoute: typeof TenantSettingsRoute
  TenantSubscriptionRoute: typeof TenantSubscriptionRoute
  TenantSupportRoute: typeof TenantSupportRoute
  TenantWebsitesRoute: typeof TenantWebsitesRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantActivityRoute: TenantActivityRoute,
  TenantAnalyticsRoute: TenantAnalyticsRoute,
  TenantBillingRoute: TenantBillingRoute,
  TenantBlogRoute: TenantBlogRoute,
  TenantBusinessRoute: TenantBusinessRoute,
  TenantDomainsRoute: TenantDomainsRoute,
  TenantFormsRoute: TenantFormsRoute,
  TenantKbRoute: TenantKbRoute,
  TenantMediaRoute: TenantMediaRoute,
  TenantPagesRoute: TenantPagesRoute,
  TenantSeoRoute: TenantSeoRoute,
  TenantSettingsRoute: TenantSettingsRoute,
  TenantSubscriptionRoute: TenantSubscriptionRoute,
  TenantSupportRoute: TenantSupportRoute,
  TenantWebsitesRoute: TenantWebsitesRoute,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CreateAccountRoute: CreateAccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundCancellationPolicyRoute: RefundCancellationPolicyRoute,
  SignInRoute: SignInRoute,
  TemplatesRoute: TemplatesRoute,
  TenantRoute: TenantRouteWithChildren,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyPasswordResetRoute: VerifyPasswordResetRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  TenantBuilderIdRoute: TenantBuilderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
